name: Go Bump Version
description: Action to bump the version of a Go project
inputs:
  pat:
    description: PAT for accessing the application repo
    required: true
  new-version:
    description: The new version to bump to
    required: true
  is-lib:
    description: Whether the project is a library
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Check if version starts with v for a library
      if: ${{ inputs.is-lib }} == "true"
      run: |
        if [[ ${{ inputs.new-version }} != v* ]]; then
          echo "Version for a go library should start with v like v1.0.0 and not 1.0.0"
          exit 1
        fi
      shell: bash
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.pat }}

    - name: Bump VERSION file
      run: |
        echo ${{ inputs.new-version }} > VERSION
      shell: bash

    - name: Bump image tags in helm values
      run: |
        if [ -f "./charts/values.dev.yaml" ]; then
        yq -i '.image.tag = "${{ inputs.new-version }}"' './charts/values.dev.yaml'
        fi
        if [ -f "./charts/values.prod.yaml" ]; then
        yq -i '.image.tag = "${{ inputs.new-version }}"' './charts/values.prod.yaml'
        fi
        if [ -f "./charts/values.stage.yaml" ]; then
          yq -i '.image.tag = "${{ inputs.new-version }}"' './charts/values.stage.yaml'
        fi
      shell: bash
    
    - name: Commit Changes
      env:
        GIT_AUTHOR_NAME: Beez Innovation Labs
        GIT_COMMITTER_NAME: Beez Innovation Labs
        GIT_AUTHOR_EMAIL: github@beezlabs.com
        GIT_COMMITTER_EMAIL: github@beezlabs.com
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "feat: bump version to ${{ inputs.new-version }}"
        git push
      shell: bash
